#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

YELLOW='\033[1;33m'
RESET='\033[0m'

echo "${YELLOW}[HUSKY]${RESET} Running linters..."

PACKAGE_MANAGER=yarn
if ! command -v $PACKAGE_MANAGER &> /dev/null
then
	PACKAGE_MANAGER=npm
fi

$PACKAGE_MANAGER run lint:no-fix

echo "${YELLOW}[HUSKY]${RESET} Finished project linting."
